Moving hardcoded messages to US and KR properties
epicarts/fosslight pull request #12
Opened 2021-10-12 03:52 UTC by chd830

## Description
The hard-coded code in the jsp file under views.admin.common was added to en.properties and ko.properties.

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2021-10-12 03:54 UTC, chd830 commented on src/main/resources/messages/message_ko_KR.properties
> +msg.common.report.select.sheet=한 개 이상의 시트를 선택해 주세요.
```suggestion
```

2021-10-12 03:57 UTC, chd830 commented on src/main/resources/messages/message_en_US.properties
>  msg.distribute.sync.addedmodel=There are models added to the OSDD system. <br/>Please check the model information and try again.<br/>
```suggestion
msg.distribute.sync.addedmodel=There are models added to the OSDD system. <br/>Please check the model information and try again.<br/>
msg.distribute.description.duplicate=The same category, same description already distributed in
msg.distribute.origin.link=<a class=tabLink href=#none onclick="createTabInFrame(''{0}_Distribute'', ''#/project/distribution/{0}'')">&lt;project id: {0}&gt;</a>
```

2021-10-13 03:48 UTC, epicarts requested changes

2021-10-13 03:48 UTC, epicarts commented on src/main/resources/messages/message_en_US.properties
> +msg.distribute.confrim.overwritefile = \ub3d9\uc77c\ud55c Category\uc5d0 \ub3d9\uc77c\ud55c \uc774\ub984\uc758 \ud30c\uc77c(<b>{0}<b/>)\uc774 \uc774\ubbf8 \uc874\uc7ac\ud569\ub2c8\ub2e4. <span style=
유니코드 없이 아래와 같이 나와야합니다. 수정 부탁드려요.

```suggestion
msg.distribute.confrim.overwritefile=File(<b>{0}<b/>) with the same name already exists in the category. <span style="color:red;">Do you want to overwrite <b>{0}<b/> file?</span><br>(If you change the file, it applies to <span style="color:blue;">all relevant models that already distributed.</span>)
```

2021-10-13 03:48 UTC, epicarts commented on src/main/resources/messages/message_ko_KR.properties
> +msg.common.cannot.registered.delete=등록된 라이센스는 삭제가 불가능 합니다.
라이센스 -> 라이선스로 수정 부탁드려요.

2021-10-13 03:48 UTC, epicarts commented on src/main/resources/messages/message_ko_KR.properties
> +msg.oss.include.license=본 OSS는 여러 License 하의 Source Code를 포함하고 있습니다.
License => 라이선스, Source Code => 소스 코드

2021-10-13 03:48 UTC, epicarts commented on src/main/resources/messages/message_ko_KR.properties
> +msg.oss.select.license=본 OSS는 등록된 License 중 하나를 선택할 수 있습니다.
License => 라이선스 위와 같습니다~

2021-10-14 15:05 UTC, epicarts approved these changes

2021-10-15 05:23 UTC, chd830 commented on src/main/resources/messages/message_ko_KR.properties
> +invalid.email.error=잘못된 이메일 주소입니다.
```suggestion
invalid.email.error=유효하지 않은 이메일 주소입니다.
```

2021-10-15 05:23 UTC, chd830 commented on src/main/resources/messages/message_ko_KR.properties
> +enter.watcher.error=Watcher AD ID를 입력하세요.
```suggestion
enter.watcher.error=Watcher의 AD ID를 입력하세요.
```

2021-10-15 05:23 UTC, chd830 commented on src/main/resources/messages/message_ko_KR.properties
> +msg.partner.warning=3rd party software 상태가 다른 사용자에 의해 변경되고 있습니다. 자세한 내용은 reviewer에게 문의하세요.
```suggestion
msg.partner.warning=Reviewer에게 문의하세요.
```

2021-10-15 05:23 UTC, chd830 commented on src/main/resources/messages/message_ko_KR.properties
> +msg.partner.delete.warning=파티를 삭제하시겠습니까?\n(데이터가 영구적으로 삭제됩니다.)
```suggestion
msg.partner.delete.warning=해당 데이터가 영구적으로 삭제됩니다. 그래도 진행하시겠습니까?
```

2021-10-15 05:45 UTC, epicarts approved these changes

2021-10-16 05:03 UTC, merged